# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Learning Log
author:
  name: Max Lepper
  email: incoming+maxlepper-learning-log-20414833-issue-@incoming.gitlab.com
  site: https://maxlepper.me
description: >- # this means to ignore newlines until "baseurl:"
  Max Lepper's Web Development Skill Journal
baseurl: "/learning-log" # the subpath of your site, e.g. /blog
url: "https://maxlepper.gitlab.io" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: /:slugified_categories/:year/:month/:day/:title
show_excerpts: true
google_analytics: UA-174987278-1

# Collection Structure
collections:
  skills:
    output: true
    permalink: /:collection/:name

# Theme
theme: minima # https://github.com/jekyll/minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    personal: https://maxlepper.me
    github: lepperm
    linkedin: maxlepper
    gitlab:
      - username: maxlepper
        instance: gitlab.com
    stackoverflow: 14096749/max-l
    codepen: lepperm
# On my local PC, the Minima theme assets can be found at \Programs\Ruby27-x64\lib\ruby\gems\2.7.0\bundler\gems\minima-49f6dce0727a
# To modify, copy assets to the site directory and override

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-pwa-plugin # https://github.com/lavas-project/jekyll-pwa
# - jekyll-compose # Command plugin to help with writing posts https://github.com/jekyll/jekyll-compose
# - jekyll-gzip # Seems more full-featured than my CI line, look into and test! https://github.com/philnash/jekyll-gzip
# - jemoji # https://github.com/jekyll/jemoji
# - jekyll-archives # https://github.com/jekyll/jekyll-archives
# - jekyll-assets # https://github.com/envygeeks/jekyll-assets/blob/master/README.md

# jekyll-pwa-plugin configuration
pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 10 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "assets/**/**/*.{js,css,eot,svg,ttf,woff,ico}"
    - index.html
    - "**/index.html"
  precache_glob_ignores: # Optional
    - sw-register.js

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: learning-log

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
